[env]
TERM = "xterm-256color"

[window]
opacity = 1

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
size = 14

[cursor]
style = { shape = "Block", blinking = "On" }

[terminal]
shell = "/usr/bin/zsh"

# Default colors
[colors.primary]
background = '#292C3E'
foreground = '#EBEBEB'

# Cursor colors
[colors.cursor]
text = '#EBEBEB'
cursor = '#FF261E'

# Normal colors
[colors.normal]
black   = '#0d0d0d'
red     = '#FF301B'
green   = '#A0E521'
yellow  = '#FFC620'
blue    = '#1BA6FA'
magenta = '#8763B8'
cyan    = '#21DEEF'
white   = '#EBEBEB'

# Bright colors
[colors.bright]
black   = '#6D7070'
red     = '#FF4352'
green   = '#B8E466'
yellow  = '#FFD750'
blue    = '#1BA6FA'
magenta = '#A578EA'
cyan    = '#73FBF1'
white   = '#FEFEF8'

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"


[[hints.enabled]]
command         = "xdg-open"
hyperlinks      = false
post_processing = true
persist         = false
mouse.enabled   = true
mouse.mods      = "Control"
binding         = { key = "O", mods = "Control|Shift" }
regex           = "(mailto:|https://|http://|file:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
